# Generated by Django 2.0.3 on 2020-04-14 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
